# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build dex-tools with Gradle
      run: ./gradlew check distZip

    - uses: ncipollo/release-action@v1
      with:
        tag: v${{ github.run_number }}
        artifacts: dex-tools/build/distributions/dex-tools-2.1-SNAPSHOT.zip

    - name: Archive dex tools
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: dex-tools-2.1-SNAPSHOT
        path: dex-tools/build/distributions/dex-tools-2.1-SNAPSHOT.zip
